-- Seed complet des races basé sur races.html
-- À exécuter dans Supabase → SQL Editor

INSERT INTO races (slug, data) VALUES

('humains', jsonb_build_object(
  'nom', 'Humains et Humanoïdes',
  'couleur', '#F4BEE9',
  'image', 'humain.jpeg',
  'population', 203500,
  'esperanceVie', '80 ans',
  'description', '<p>Sédentaires ou nomades, les humains ne vivent quasiment jamais seuls — ils se retrouvent toujours dans de plus ou moins grandes communautés. Vivant dans les villes comme parfois en autarcie, les humains sont souvent représentés comme une race intelligente.</p><p>Les humanoïdes peuvent être catégorisés en deux sous-races : les humains dits <strong>normaux</strong> et les <strong>mages</strong>. Les humains normaux n''ont pas vraiment de capacités propres, à part celle de vivre pleinement parmi des races toutes plus puissantes. Quant aux mages, ils ont la capacité d''utiliser la magie et représentent près de <strong>35 %</strong> de la population humaine — cette différence est innée. Enfin, les <strong>sorciers</strong> représentent moins de 5 % des humains : bien que rares, ils peuvent développer un pacte avec les Ryximus ce qui leur permet d''acquérir la magie.</p><p>Il y a de nombreux moyens de tuer un humain : une chute, une balle dans la tête, un pieu dans le cœur — toutes les choses classiques.</p>',
  'histoire', '<p>On raconte que les humains ont été façonnés par les Ryximus à partir des éléments existants en <strong>l''an 250</strong>. Très vite, ils se reproduisirent et commencèrent à fonder des clans épars sur le continent vierge. De par leurs actions, certains devinrent les préférés des Ryximus qui leur accordèrent l''accès à la magie. Au fil des générations, la magie se transmit et se répandit — mais pas toujours fidèlement, créant des mages dans des familles ordinaires et inversement.</p><p>Petit à petit, une hiérarchie se mit en place et un royaume prit forme dans les années <strong>490</strong> : la <strong>Grande Dynastie</strong>, gouvernée par un empereur dont l''histoire oublia le nom. Elle dura près de deux siècles. Durant ce laps de temps, les mages et les humains normaux se séparèrent — une théorie émergea selon laquelle le mélange de leurs sangs ferait perdre la magie à la descendance, entraînant discrimination des deux côtés.</p><p>Une décennie de mauvaises récoltes et les tensions ambiantes plongèrent le royaume dans la crise. Un coup d''État eut lieu en <strong>l''an 700</strong>, mettant fin à la Grande Dynastie.</p><p>Quelques décennies plus tard, <strong>l''Empire</strong> vit le jour, dirigé par <strong>l''impératrice Vivynotta Reichauss</strong>, aussi sévère que juste. Elle fut la première humaine à devenir sorcière grâce à un pacte avec les Ryximus, instaurant une forme de paix entre humains et mages malgré des préjugés persistants. L''Empire tomba en <strong>l''an 906</strong>, donnant naissance d''un côté au Saint Empire, de l''autre à Lyndera.</p><p>Le pays de <strong>Silfus</strong> est mentionné pour la première fois en <strong>l''an 1112</strong>. D''abord gouverné par les De Nolid, la branche royale passa aux <strong>Ginaldus</strong> en l''an 1305, qui gouvernent depuis. Silfus accueille aujourd''hui toutes les races volontiers.</p>',
  'magie', '<p>Les mages (35 % de la population) peuvent utiliser tout type de magie. Les humains normaux n''en possèdent aucune — sauf les <strong>sorciers</strong> (moins de 5 %), qui peuvent développer un pacte avec un Ryximus pour acquérir la magie. Ces pactes sont rares et leur nature varie selon le Ryximus concerné.</p>',
  'societe', '<p>Les humains vivent en communautés organisées, avec des structures sociales allant de la monarchie à la démocratie selon le pays. Ils constituent la majorité de la population dans Silfus et Frimaz, occupant des rôles très variés, du noble au paysan.</p>',
  'physique', '<p>Taille moyenne de <strong>1,60 m</strong> pour les femmes et <strong>1,70 m</strong> pour les hommes. Leurs cheveux peuvent avoir une multitude de couleurs, allant du blond au brun en passant par le roux et le châtain. Leurs yeux sont bleus, verts ou marrons. Leur corpulence est très variable, allant de très maigre à l''obésité.</p>'
)),

('elfes', jsonb_build_object(
  'nom', 'Elfes',
  'couleur', '#D4BAF7',
  'image', 'elfe.jpeg',
  'population', 226000,
  'esperanceVie', '500 ans (1 an elfe = 6,25 ans humains)',
  'description', '<p>La plupart des elfes demeurent dans de petits villages forestiers camouflés à travers les arbres. Ils chassent le gibier, font la cueillette et cultivent les légumes. Leurs compétences et leur magie leur permettent de vivre en autarcie sans avoir à défricher la terre. Ce sont des artisans doués qui fabriquent des vêtements finement tissés et des objets d''art.</p><p>Les contacts avec le monde extérieur sont ordinairement limités — bien qu''un petit nombre d''elfes gagnent leur vie en échangeant des œuvres artisanales contre des métaux. Les elfes rencontrés hors de leurs territoires sont habituellement des ménestrels, des artistes ou des érudits. La noblesse humaine s''arrache les services de tuteurs elfiques pour l''enseignement de l''escrime ou de la magie.</p><p>Les elfes sont particulièrement doués pour le tir à l''arc et ont une ouïe surdéveloppée. Ce sont aussi des maîtres dans l''art du camouflage. Connus pour leur nature hautaine envers les autres races, ils sont naturellement gracieux et paraissent d''une beauté envoûtante. Ils sont légèrement plus grands qu''un humain moyen, entre 1,70 m et 1,90 m, plus sveltes, hommes et femmes de tailles similaires.</p><p>Les sons trop forts ou trop aigus peuvent les étourdir. En dehors de la forêt, ils perdent leur avantage stratégique. Ils ont également une tendance à la claustrophobie.</p>',
  'histoire', '<p>Il est dit dans les légendes qu''un groupe d''humains, plus proches de la nature que leurs congénères, décidèrent de partir habiter la grande forêt d''Ilonaï aux environs de <strong>l''an 310</strong>. Après cinq ou six générations, désormais adaptés à la vie en nature, ces humains prièrent les Ryximus pour de meilleures adaptations. C''est ainsi que naquirent les premiers elfes en <strong>l''an 445</strong>.</p><p>Organisés autour d''une monarchie, les elfes ont petit à petit commencé à migrer chacun dans de petits villages, complètement coupés du reste du monde. Il est extrêmement difficile d''entrer dans un village elfe sans invitation. De nos jours, ils vivent paisiblement en autarcie.</p>',
  'magie', '<p>Près de <strong>80 %</strong> de la population elfique maîtrise la magie. Ils maîtrisent bien souvent une magie élémentaire (eau, air, terre et feu) ainsi que la magie de la nature, étant donné qu''ils vivent en harmonie avec elle. Leur maîtrise de ces éléments leur permet de tirer des flèches élémentaires, de faire des pièges, de détecter les vibrations de la terre ou dans l''air, etc.</p>',
  'societe', '<p>Les elfes vivent en communautés forestières autarciques, hermétiquement closes au monde extérieur. Ils privilégient les vêtements élégants de couleurs ternes et naturelles et apprécient le port de bijoux simples. Lorsqu''ils sont dans des endroits emplis de gens qui ne sont pas des elfes, ils ont tendance à être mal à l''aise.</p><p>Les elfes, moins portés sur l''acte sexuel et la reproduction, ont en général deux à trois enfants au cours de leur longue vie — la population maintient ainsi toujours plus ou moins son nombre.</p>',
  'physique', '<p>Leur apparence est très semblable aux humains. La plus grande différence réside dans leurs <strong>longues oreilles pointues</strong>. On note également une légère différence de taille, les elfes ayant tendance à être sensiblement plus grands — entre <strong>1,70 m et 1,90 m</strong> — et plus sveltes que les humains. Hommes et femmes sont de tailles similaires, les hommes à peine plus massifs.</p>'
)),

('sakennapies', jsonb_build_object(
  'nom', 'Sakenpapiés',
  'couleur', '#FAEEB0',
  'image', 'sakenpapié.jpeg',
  'population', 92000,
  'esperanceVie', '350 ans (1 an = 4,37 ans humains)',
  'description', '<p>Les Sakenpapiés vivent dans de très petits villages qu''on pourrait presque qualifier de hameaux, et vivent de l''agriculture et de la chasse, dans le respect de leur environnement. Leur capacité à utiliser la magie est innée, et c''est donc très jeunes qu''ils commencent à participer aux tâches dans le village. Il n''y a aucune hiérarchie dans leur race — tous les Sakenpapiés sont égaux. Ils vivent beaucoup à base d''échanges.</p><p>Ils sont capables de contrôler leur élément à la perfection, mais ne peuvent en maîtriser qu''un seul — sauf exceptions extrêmement rares.</p>',
  'histoire', '<p>Quand les humains naquirent, <strong>Whimir</strong> fût fascinée par ces petits êtres. Elle les observa longtemps, jusqu''à ce qu''une idée lui vînt : créer une race semblable aux humains, mais sans leurs imperfections. Elle en parla à Galdros, qui fut enthousiaste. Les Ryximus se scindèrent en deux camps : Galdros, Nyrel et Sylvaë soutenant le projet, et Zoggan, Vespera, Noctis et Ignir refusant.</p><p>Whimir, moins expérimentée que ses frères et sœurs, déversa trop de magie dans le premier être en cours de création. Le corps en formation se déforma, la magie en surplus tentant de s''échapper. Finalement, une excroissance se forma sur le front du petit être — la première corne. Effrayée, Whimir réalisa que le surplus de magie était logé dans cette corne. Ainsi naquit le premier Sakennapié.</p><p>Vers <strong>l''an 500</strong>, devenus relativement nombreux, certains Sakenpapiés décidèrent d''instaurer une hiérarchie basée sur le nombre et la taille de l''excroissance de naissance. Le traitement imposé à la basse classe était difficilement supportable, et une rébellion éclata. C''est au cours de cette longue guerre civile qu''ils commencèrent à être sévèrement chassés et réduits en esclavage pour leurs cornes, utilisées en alchimie et en remèdes. Une fois la rébellion terminée, il fut décidé qu''ils porteraient désormais de quoi se cacher le visage afin de minimiser les risques d''attaque. Ils commencèrent alors à s''éparpiller sur le continent et à vivre discrètement.</p>',
  'magie', '<p><strong>99 %</strong> de la population est mage. Chaque Sakennapié maîtrise <strong>un seul élément</strong> à la perfection grâce à sa corne primaire, qui agit comme un second réservoir de magie.</p><p>Les excroissances poussant sur le corps des Sakenpapiés viennent de leurs blessures passées — sauf la première, programmée pour croître dès les premiers mois de vie jusqu''à la fin de la puberté, généralement sur la tête. Les blessures superficielles ne produisent pas de cornes ; toute blessure laissant s''échapper une certaine quantité de sang en entraînera une. Briser la corne de naissance peut provoquer une perte de maîtrise magique catastrophique. Briser les autres ne provoque qu''un léger inconfort passager.</p><p>Toute blessure guérie par un sort ou une potion ne laissera apparaître aucune excroissance. L''utilisation d''onguents régénératifs semble diminuer leur taille.</p>',
  'societe', '<p>Les Sakenpapiés ne connaissent aucune hiérarchie — tous sont égaux. Ils vivent en hameaux discrets et fonctionnent principalement par échanges. Depuis les persécutions passées, ils portent des vêtements couvrant le visage pour se protéger.</p>',
  'physique', '<p>Semblables aux humains, ils présentent deux grandes différences : leurs <strong>excroissances</strong> (cornes poussant sur le corps suite à des blessures, ainsi que la corne de naissance) et leurs <strong>oreilles légèrement en pointe</strong>, bien moins longues que celles des elfes.</p>'
)),

('rumis', jsonb_build_object(
  'nom', 'Rumis',
  'couleur', '#FBBCBC',
  'image', 'rumi.jpeg',
  'population', 25000,
  'esperanceVie', '~80 ans (peuvent se réincarner à l''infini)',
  'description', '<p>Les Rumis sont d''apparence totalement humains — singulièrement beaux, même. Ils vivent parmi eux, sans faire de remous afin de se fondre dans la masse. Ils sont souvent dans des actions caritatives visant à aider les plus démunis.</p><p>Ils ne peuvent pas manger de nourriture humaine (ou seulement en infime quantité), puisqu''ils se nourrissent d''<strong>âmes</strong>. Sans fuir le soleil, ce peuple y est très sensible — il les affaiblit fortement et provoque de gros coups de soleil. Ils apprécient le froid et sont fragilisés à l''exposition de la chaleur.</p><p>Il y a deux camps : ceux qui vivent en marge de la société à <strong>Silfus</strong> — froidement chassés et exterminés par la population — et ceux pleinement intégrés dans les hautes sphères du pouvoir à <strong>Frimaz</strong>.</p>',
  'histoire', '<p>Les Rumis sont les chouchous des Ryximus, réincarnés par ces derniers pour continuer à promouvoir le bien et l''harmonie dans le monde. Lorsqu''ils donnèrent naissance à la seconde génération (les <em>naturels</em>), ils se firent vénérer comme des êtres supérieurs liés aux Ryximus.</p><p>Mais des rumeurs naissent. Selon la légende, un Rumi malveillant se mit à avaler toutes les âmes sur son chemin, n''hésitant pas à tuer des victimes innocentes, instaurant un règne de terreur qui dura près de deux siècles. Dans les faits, c''est une succession de Rumis tyranniques — mais la légende prévalut sur la réalité, entraînant la déchéance des Rumis.</p><p>Lassés d''être persécutés par une légende faussée, certains rejoignirent une colonie lointaine qui deviendra <strong>Frimaz</strong>. Leur nombre tomba à moins de trente mille. Quelques individus vivent encore à Silfus, dans une tentative de redorer leur blason — sans succès pour le moment. L''équilibre est perdu, leurs chefs sont absents.</p>',
  'magie', '<p><strong>100 %</strong> des Rumis possèdent des capacités magiques — uniquement la <strong>magie de l''esprit</strong>. Ils peuvent voir les âmes des défunts (sous forme de boule brillante ou à l''image de la personne — selon les préférences individuelles) et communiquer avec eux via un cercle utilisable uniquement par les Rumis. L''absorption des âmes leur accorde une apparence éternellement jeune tant qu''ils continuent de se nourrir. Arrêter provoque un rattrapage de l''âge réel en quelques heures — cela n''impacte que l''apparence, pas la mortalité.</p>',
  'societe', '<p>Les Rumis peuvent se reproduire de deux manières. La première, <strong>naturelle</strong>, produit des enfants appelés <em>naturels</em>. La seconde utilise un <strong>cercle de reproduction</strong> : un bébé humain est placé au centre, une âme est invoquée et prend possession du bambin, écrasant l''esprit à peine formé. Cet être devient un Rumi <em>pur</em>, conservant des bribes de sa vie précédente. Il est courant de réincarner les mêmes âmes à plusieurs reprises pour garder parmi eux des individus forts ou charismatiques.</p>',
  'physique', '<p>Semblables aux humains, leurs yeux peuvent se parer d''une palette de couleurs bien plus large que leurs congénères — c''est là la seule différence physique les séparant. Leur beauté remarquable et leur apparence éternellement juvénile (tant qu''ils se nourrissent) peuvent les trahir aux yeux des plus observateurs.</p>'
)),

('nains', jsonb_build_object(
  'nom', 'Nains',
  'couleur', '#F9D1BB',
  'image', 'nain.jpeg',
  'population', 59000,
  'esperanceVie', '350 ans (1 an nain = 4,37 ans humains)',
  'description', '<p>Les royaumes nains s''étendent loin sous les massifs montagneux où les nains exploitent des mines de pierres et de métaux précieux pour en faire des objets merveilleux. Ils aiment la beauté et les qualités artistiques des métaux précieux et des bijoux à un point tel que certains succombent à l''avarice.</p><p>S''il existe une richesse qu''ils ne peuvent trouver sous leurs montagnes, ils l''obtiennent par le commerce. Les membres fiables des autres races sont bien accueillis dans les établissements nains, bien que certaines zones ne leur soient pas accessibles. Individuellement, un nain est déterminé et loyal, fidèle à sa parole et résolu dans ses actions — au point d''être considéré comme entêté. Ils oublient lentement le mal qu''on leur a fait subir : un affront fait à un nain est un affront fait à tout son clan.</p>',
  'histoire', '<p>Il est dit que les nains ont été créés par les Ryximus à partir des différents minéraux présents dans le sol de la planète. Très vite, ils établirent <strong>six clans</strong> dont les six chefs forment le <strong>Conseil des Six</strong>. Le pouvoir des clans se transmet de génération en génération, et aucune famille n''a vécu de coup d''État jusqu''à aujourd''hui.</p>',
  'magie', '<p>Les nains ont une affinité avec la magie de la <strong>terre</strong>, mais peuvent maîtriser tout type de magie. Environ <strong>25 %</strong> de la population maîtrise la magie. Les nains ont aussi la maîtrise d''un outil d''artisan au choix : outils de forgeron, de brasseur ou de maçon.</p>',
  'societe', '<p>Organisés en clans dirigés par les anciens, les nains mettent la tradition et la loyauté familiale au premier plan. Ils respectent leurs traditions depuis la fondation de leurs bastions ancestraux. Le Conseil des Six réunit les chefs des clans. Ils commercent leurs métaux et artefacts avec les autres races — ce sont souvent des humains ou des hommes-bêtes qui font le négoce par voie maritime, les nains n''appréciant pas les bateaux.</p>',
  'physique', '<p>Trapus, les nains mesurent en moyenne <strong>1,20 m</strong> et pèsent autant qu''un humain d''un mètre de plus. Leur teint varie du brun foncé à des tons plus pâles, avec parfois un soupçon de rouge. Leur chevelure, portée longue mais simplement stylisée, est habituellement noire, grise ou brune — les nains plus pâles ont souvent les cheveux roux. Les hommes accordent une grande valeur à leur barbe et l''entretiennent avec grand soin.</p>'
)),

('poluzoanns', jsonb_build_object(
  'nom', 'Poluzoanns',
  'couleur', '#B9E5C8',
  'image', 'poluzoann.jpeg',
  'population', 82500,
  'esperanceVie', '130 ans',
  'description', '<p>La majorité d''entre eux vivent dans <strong>Silfus</strong>, et une petite partie dans la grande forêt d''Ilonaï. Il n''y a aucune hiérarchie entre eux.</p><p>Les Poluzoanns ont un ou plusieurs membres supplémentaires — les <strong>Poluzy</strong> — qui apparaissent aux environs de l''événement le plus marquant de leur vie, que ce soit en bien ou en mal. Ces membres ont leur propre conscience, variable, allant de très faible à une conscience à part entière, et sont attachés à leur maître. Les arracher peut causer leur mort.</p><p>Seul 1 Poluzoann sur 10 000 est capable de maîtriser la magie (0,01 % de la population), peu importe son type.</p>',
  'histoire', '<p>L''histoire des Poluzoanns est similaire à celle des humains, à quelques éléments majeurs près. En <strong>l''an 360</strong>, un groupe de Poluzoanns décida de monter un coup d''État contre les humains dits <em>purs</em>, se considérant supérieurs de par leurs membres supplémentaires. Cela mena à une chasse à l''homme qui dura près de <strong>quarante ans</strong>, avant que la faction coupable ne soit entièrement éradiquée par un grand mage elfe connu sous le nom d''<strong>Ezekiel de la Fraünidé</strong> — ou Ezekiel le Grand. Un Poluzoann influent, <strong>Geried Lasoll</strong>, permit de calmer les foules et d''éradiquer les derniers partisans de la Supériorité Supplémentaire.</p>',
  'magie', '<p>Seul <strong>1 Poluzoann sur 10 000</strong> est capable de maîtriser la magie, soit <strong>0,01 %</strong> de la population — peu importe le type de magie. La magie des Poluzoanns est parfois liée à leurs membres supplémentaires qui peuvent agir comme canaux magiques.</p>',
  'societe', '<p>Les Poluzoanns s''intègrent généralement dans les sociétés humaines. Leur particularité est acceptée avec plus ou moins de curiosité selon les régions. Leurs membres supplémentaires sont parfois source de fascination, parfois de méfiance. Il n''y a aucune hiérarchie interne à leur race.</p>',
  'physique', '<p>Leur caractéristique principale est leur <strong>membre supplémentaire</strong> (le Poluzy). La plupart en ont un, mais il arrive que certains en aient plus. Ces membres apparaissent lors de l''événement le plus marquant de leur vie. C''est là la seule différence avec les humains.</p>'
)),

('hommes-betes', jsonb_build_object(
  'nom', 'Hommes-Bêtes',
  'couleur', '#C8D8F0',
  'image', 'homme_bête.jpeg',
  'population', 315000,
  'esperanceVie', '30 à 180 ans selon l''espèce',
  'description', '<p>Les hommes-bêtes vivent en communauté dans leur pays, <strong>Lyndera</strong>. Ils y vivent selon la loi du plus fort, avec le fameux Arena Fight. Les espèces les plus faibles ont tendance à fuir dans des villages reculés ou dans la forêt d''Ilonaï pour ne pas se faire harceler par les races les plus fortes.</p><p>Leurs capacités varient grandement en fonction de l''animal avec lequel ils sont mélangés : sens accrus, meilleurs réflexes, plus de force, capacité de voler ou de creuser, fabrication de toile — les possibilités sont infinies. Leurs points faibles sont ceux d''un humain classique, cumulés à ceux de l''animal (il n''est pas rare de voir des mi-papillons de nuit voler autour des lampadaires).</p>',
  'histoire', '<p>Lors de la chute de l''Empire en <strong>906</strong>, le grand territoire se scinda en deux — donnant naissance d''un côté à Silfus, de l''autre à Lyndera, qui très rapidement ne se peupla presque que d''hommes-bêtes. Les règnes se succédèrent rapidement, certains ne durant que quelques heures. Celui de <strong>Gryffus</strong> sera probablement gravé dans le marbre pour le prochain millénaire : c''est lui qui décida d''instaurer l''<strong>Arena Fight</strong>, et le premier à le remporter.</p><p>L''histoire du pays se poursuit sans rien de notable jusqu''à l''émergence récente de deux factions : l''une prônant le règne par la force, l''autre préférant une approche plus civilisée et humanoïde.</p>',
  'magie', '<p>Il est très rare de voir un homme-bête maîtriser la magie — ils représentent <strong>3 %</strong> de la population. Cependant, ils semblent avoir une affinité particulière avec la <strong>magie de la nature</strong>, plus qu''avec les autres types. Ils peuvent tout de même maîtriser tout type de magie.</p>',
  'societe', '<p>Organisés selon la loi du plus fort, avec l''Arena Fight comme institution centrale à Lyndera. Les espèces moins puissantes fuient vers les marges. La société se structure en meutes, hardes ou clans selon la nature animale de chacun. Deux factions politiques émergentes s''affrontent sur la direction du pays.</p>',
  'physique', '<p>Leurs particularités physiques sont aussi variables qu''il existe d''animaux sur le continent. Certains n''héritent que d''un trait ou deux de leur partie animale, là où d''autres sont un animal humanisé. Il est donc difficile de dresser une liste exhaustive — la diversité est totale.</p>'
))

ON CONFLICT (slug) DO UPDATE SET data = EXCLUDED.data;
