-- ============================================================
-- MINAMIX WIKI — Seed (données initiales)
-- À exécuter APRÈS schema.sql dans l'éditeur SQL Supabase
-- ============================================================

-- ── Pays ──────────────────────────────────────────────────────

insert into public.pays (slug, data) values
('silfus', '{
  "nom": "Silfus",
  "couleur": "#4D77DB",
  "geographie": "Silfus possède des frontières terrestres avec Lyndera et Ilonaï. Son territoire est principalement plat avec quelques collines éparses, organisé autour de la rivière Lizieu, du canal Paisible et du lac Curato. Le climat y est océanique.",
  "histoire": "Vers l''an 250, les Ryximus créent les humains. La Grande Dynastie s''établit, marquée par des conflits entre mages et non-mages. Après sa chute en l''an 700, l''Empire sous l''Impératrice Vivynotta Reichauss prend le relais. Silfus est fondé en 1112 sous la famille De Nolid, puis passe aux Ginaldus en 1205.",
  "politiqueInterne": "Silfus est gouverné par un Roi qui arbitre entre le Conseil des Six familles : Sapienthys (Éducation et Recherche), Statera (Justice et Affaires étrangères), Exercitus (Intérieur et Armées), Laboren (Travail et Santé), Thesaurus (Économie et Finances), Agros (Culture et Agriculture).",
  "politiqueExterne": "Les relations avec Lyndera sont marquées par des tensions diplomatiques autour de la cité-État de Frimaz. Ilonaï est ignorée. Les tensions avec Frimaz portent sur le commerce et les intérêts militaires.",
  "modeDeVie": "La technologie est comparable au Moyen-Âge. La magie est intégrée dans la vie quotidienne avec une accessibilité variable selon la classe sociale. La médecine repose sur les remèdes à base de plantes et les pratiques traditionnelles.",
  "traditions": [
    {"nom": "Le Rite", "description": "Compétition bisannuelle pour les jeunes mages."},
    {"nom": "La Communion", "description": "Festival annuel d''une semaine pour remercier les éléments de la nature."},
    {"nom": "Tasi", "description": "Tradition de dons basée sur la légende de deux amants des clans de lumière et d''obscurité."}
  ],
  "societe": "Trois classes sociales : nobles et riches (moins de 15 %), bourgeoisie et classe moyenne (environ 30 %), peuple commun (environ 55 %)."
}'),
('lyndera', '{
  "nom": "Lyndera",
  "couleur": "#BA7F23",
  "geographie": "Lyndera possède une frontière terrestre avec Silfus et une frontière maritime avec Ilonaï. Le terrain est montagneux, variant de 1 300 à 4 800 mètres. Les populations naines habitent des galeries souterraines. Le climat est frais avec la rivière Sableuse comme voie d''eau principale.",
  "histoire": "Lyndera partage une histoire similaire à Silfus jusqu''en l''an 906. La région a traversé l''Ère des Ténèbres avant de se stabiliser vers l''an 950 sous l''Alpha Nomaz Tioùa et la guilde de la Bête Rugissante. Plusieurs coups d''État ont mené à l''instauration des tournois de l''Arène en 1102 pour désigner les dirigeants.",
  "politiqueInterne": "Monarchie absolue avec le Roi assisté d''un Triumvirat de trois conseillers de confiance sélectionnés via le tournoi Phaeton. La société est organisée en clans dirigés par des chefs qui maintiennent une semi-autonomie sous la tutelle royale.",
  "politiqueExterne": "Les relations avec Silfus sont froides. Lyndera considère Ilonaï comme un territoire à conquérir pour ses ressources. Frimaz est ciblée pour une influence diplomatique et économique.",
  "modeDeVie": "La technologie reste rudimentaire, axée sur l''artisanat, notamment la métallurgie et la fabrication d''armes. L''architecture est fortifiée. Solvernia est la ville principale avec des quartiers organisés par clans.",
  "traditions": [
    {"nom": "Arena Fight", "description": "Tournoi annuel déterminant la direction du pays."},
    {"nom": "Phaeton", "description": "Tournoi pour sélectionner le Triumvirat (22-24 septembre)."},
    {"nom": "Aurae", "description": "Saison des amours au printemps."},
    {"nom": "Tasi", "description": "Tradition de dons."}
  ],
  "societe": "Structure hiérarchique basée sur la dynamique prédateur-proie. Les autres races sont tolérées mais subordonnées. Les clans familiaux sont fondamentaux. L''éducation est pratique et martiale."
}'),
('frimaz', '{
  "nom": "Frimaz",
  "couleur": "#72A06E",
  "geographie": "Frimaz borde Silfus et Ilonaï par voie terrestre et maritime. Le terrain est relativement plat avec deux à trois collines, une mine et un climat continental organisé autour du canal Paisible.",
  "histoire": "Initialement partie de la forêt d''Ilonaï, Frimaz déclare son indépendance vers l''an 300 sous Friedrich Dolagan. Après des siècles d''occupation, une révolution démocratique en l''an 830 renverse la monarchie et établit une république.",
  "politiqueInterne": "République démocratique avec deux Consuls (mandats d''un an) comme exécutifs, un Sénat de vingt membres (mandats de trois ans) avec pouvoir législatif, des Magistrats gérant des domaines spécifiques, un système judiciaire indépendant et une Assemblée Populaire permettant l''expression citoyenne.",
  "politiqueExterne": "Commerce modéré avec Silfus. Relations tendues avec Lyndera en raison des occupations passées. Échanges fréquents mais informels avec Ilonaï.",
  "modeDeVie": "Technologiquement avancée avec des systèmes d''égouts, des réseaux hydrauliques et des armes à poudre noire. L''architecture présente des bâtiments en pierre à plusieurs étages avec une infrastructure sophistiquée.",
  "traditions": [
    {"nom": "Konoka", "description": "Compétition trimestrielle d''entrée militaire pour les jeunes mages."},
    {"nom": "Exposition annuelle", "description": "Vitrine technologique annuelle (fin mars)."},
    {"nom": "Tasi", "description": "Tradition de dons."}
  ],
  "societe": "Nobles et riches (20 %), bourgeoisie et classe moyenne (40 %), peuple commun (40 %) engagé dans le travail manuel et de services."
}'),
('ilonai', '{
  "nom": "Ilonaï",
  "couleur": "#B71414",
  "geographie": "Ilonaï borde Frimaz et Silfus. Plus de la moitié du territoire est couvert de forêts denses (climat méditerranéen). Les zones restantes ont un climat continental avec quelques reliefs, organisées autour de la Rivière Défendue et du Lac d''Olfatra.",
  "histoire": "Territoire indépendant avec sa propre tradition monarchique jusqu''à la désastreuse gouvernance du Roi Trumpet en l''an 870 qui provoqua une rébellion. Durant plus de deux siècles, divers systèmes politiques échouèrent. La population finit par se fragmenter en villages autonomes et tribus nomades.",
  "politiqueInterne": "Aucun gouvernement centralisé. Divisée en clans indépendants utilisant leurs propres systèmes de gouvernance, avec des décisions prises collectivement ou par l''autorité clanique traditionnelle.",
  "politiqueExterne": "Ignorée par Silfus. Vue avec suspicion par Lyndera en raison de prétendues ambitions territoriales. Maintient des relations commerciales pratiques mais informelles avec Frimaz.",
  "modeDeVie": "Technologie simple et durable axée sur le tir à l''arc, les remèdes à base de plantes et l''artisanat du bois. Les habitats s''intègrent dans la nature à travers des villages dans les arbres, des habitations en flanc de colline et des campements temporaires.",
  "magie": "La magie est intuitive, basée sur les émotions et liée à la nature plutôt qu''à l''étude académique. Il n''y a pas d''académies ; les anciens guident les jeunes praticiens. La magie évite la destruction et met l''accent sur l''équilibre naturel.",
  "traditions": [
    {"nom": "Shyke", "description": "Dernier jour de récolte pour remercier les Ryximus et les agriculteurs."},
    {"nom": "Solstices et Équinoxes", "description": "Quatre célébrations saisonnières avec repas, vêtements et danses traditionnels."},
    {"nom": "Tasi", "description": "Tradition de dons."}
  ],
  "societe": "Communautés diverses basées sur les clans avec des structures familiales élargies. Les rôles sont assignés par l''âge et l''expérience. L''éducation est pratique et orale. Plus grande tolérance raciale que dans les pays voisins."
}')
on conflict (slug) do nothing;

-- ── Races ─────────────────────────────────────────────────────

insert into public.races (slug, data) values
('humains', '{"nom":"Humains et Humanoïdes","couleur":"#F4BEE9","image":"humain.jpeg","population":203500,"esperanceVie":"80 ans","description":"Les humains sont des êtres communautaires, sédentaires ou nomades selon leur mode de vie. Ils forment la base des sociétés de Minamix.","histoire":"Créés par les Ryximus vers l''an 250, les humains ont rapidement formé des civilisations organisées. Ils ont connu des périodes de conflits entre mages et non-mages avant de s''établir dans leurs nations actuelles.","magie":"Environ 35 % des humains sont des mages capables d''utiliser la magie innée. Les autres peuvent devenir sorciers en passant un pacte avec un Ryximus. Ils possèdent des affinités élémentaires variées.","societe":"Les humains vivent en communautés organisées, avec des structures sociales allant de la monarchie à la démocratie selon le pays. Ils constituent la majorité de la population dans Silfus et Frimaz.","physique":"Apparence humaine classique, avec une grande diversité de traits physiques selon leur origine géographique. Taille moyenne de 1,6 à 1,85 mètre."}'),
('elfes', '{"nom":"Elfes","couleur":"#D4BAF7","image":"elfe.jpeg","population":226000,"esperanceVie":"500 ans","description":"Les elfes sont des artisans forestiers aux sens aiguisés. Excellents archers, ils vivent en harmonie avec la nature dans les forêts de Minamix.","histoire":"Parmi les premières races créées, les elfes ont développé une culture riche axée sur l''art et la nature. Ils ont maintenu leur indépendance en habitant les forêts profondes, loin des conflits politiques des nations humaines.","magie":"80 % des elfes sont des mages avec des affinités naturelles pour la magie élémentaire et naturelle. Leur longue vie leur permet de maîtriser des sorts complexes que peu d''autres races peuvent atteindre.","societe":"Les elfes vivent en communautés forestières dirigées par des anciens. Ils sont reconnus pour leur artisanat exceptionnel et leur maîtrise du tir à l''arc. Ils sont légèrement claustrophobes et mal à l''aise hors des forêts.","physique":"Grands et élancés, avec des oreilles pointues caractéristiques. Leurs sens (vue, ouïe, odorat) sont bien supérieurs à ceux des humains. Taille moyenne de 1,75 à 2 mètres."}'),
('sakennapies', '{"nom":"Sakenpapiés","couleur":"#FAEEB0","image":"sakenpapié.jpeg","population":92000,"esperanceVie":"350 ans","description":"Les Sakenpapiés sont des humanoïdes dotés de cornes et d''une capacité magique innée remarquable. Chacun maîtrise un seul élément avec une perfection absolue.","histoire":"Race mystérieuse aux origines anciennes, les Sakenpapiés ont toujours été perçus comme des êtres magiques par excellence. Leur corne primaire, réservoir de mana, est au cœur de leur identité et de leur culture.","magie":"Chaque Sakenpapié contrôle un seul élément avec une perfection absolue grâce à sa corne primaire qui agit comme réservoir magique. Leur capacité magique est innée à 100 % et ne nécessite pas d''apprentissage académique.","societe":"Les Sakenpapiés forment des communautés soudées organisées autour de leurs affinités élémentaires. Ils sont respectés pour leurs capacités magiques uniques et jouent souvent un rôle de médiateurs ou de gardiens dans les conflits.","physique":"Humanoïdes avec une ou plusieurs cornes sur la tête. La corne principale est un organe magique actif. Leur apparence est proche des humains à l''exception de leurs cornes distinctives."}'),
('rumis', '{"nom":"Rumis","couleur":"#FBBCBC","image":"rumi.jpeg","population":25000,"esperanceVie":"Indéterminée","description":"Les Rumis sont des humanoïdes qui se nourrissent d''essence spirituelle plutôt que de nourriture physique. Ils apparaissent magnifiquement humains mais consomment les âmes pour survivre.","histoire":"Rares et mystérieux, les Rumis ont toujours existé en marge des sociétés. Leur nature particulière les a souvent conduits à se cacher parmi les humains, adoptant leurs coutumes tout en préservant leur mode de vie secret.","magie":"100 % des Rumis possèdent des capacités magiques. Ils maintiennent leur apparence juvénile grâce à leur alimentation en essence spirituelle. Leur connexion avec les âmes leur confère des pouvoirs uniques liés à l''esprit.","societe":"En raison de leur nature, les Rumis vivent souvent en solitaires ou en petits groupes discrets. Ils se fondent dans la population humaine, adoptant des identités diverses au fil de leur longue existence.","physique":"Indistinguables des humains à première vue. Leur beauté remarquable et leur apparence éternellement juvénile peuvent les trahir aux yeux des plus observateurs. Ils ne vieillissent pas tant qu''ils se nourrissent régulièrement."}'),
('nains', '{"nom":"Nains","couleur":"#F9D1BB","image":"nain.jpeg","population":59000,"esperanceVie":"350 ans","description":"Les Nains sont des artisans montagnards habiles dans la métallurgie et la taille de la pierre. Organisés en clans, ils valorisent la tradition et la loyauté au-dessus de tout.","histoire":"Habitants des montagnes depuis les origines de Minamix, les Nains ont développé une civilisation souterraine florissante. Leurs galeries et cités souterraines sous Lyndera sont parmi les merveilles architecturales du monde.","magie":"Les Nains ont une affinité naturelle pour la magie de la terre et de la forge. Bien que moins nombreux à être mages que d''autres races, ceux qui le sont excellent dans la création d''objets magiques et les enchantements durables.","societe":"Organisés en clans dirigés par des anciens, les Nains mettent la tradition et la loyauté familiale au premier plan. Leurs cités souterraines sont des merveilles d''ingénierie. Ils commercent leurs métaux et artefacts avec les autres races.","physique":"Petits et trapus, environ 1,2 mètre de haut, mais d''une force physique impressionnante. Leur endurance et leur résistance sont légendaires. Ils portent souvent barbes et tresses élaborées comme symboles de statut."}'),
('poluzoanns', '{"nom":"Poluzoanns","couleur":"#B9E5C8","image":"poluzoann.jpeg","population":82500,"esperanceVie":"Proche des humains","description":"Les Poluzoanns sont des humains avec des membres supplémentaires qui se manifestent lors d''événements significatifs de leur vie. Ces appendices possèdent un niveau de conscience indépendant.","histoire":"Race relativement récente dans l''histoire de Minamix, les Poluzoanns sont apparus comme une évolution ou mutation des humains. Leurs membres supplémentaires sont considérés comme des compagnons spirituels ou des extensions de leur âme.","magie":"La magie des Poluzoanns est souvent liée à leurs membres supplémentaires qui agissent comme des canaux magiques indépendants. Cette particularité leur permet des utilisations magiques créatives impossibles pour les autres races.","societe":"Les Poluzoanns s''intègrent généralement dans les sociétés humaines, leur particularité étant acceptée avec plus ou moins de curiosité selon les régions. Leurs membres supplémentaires sont parfois source de fascination, parfois de méfiance.","physique":"Apparence humaine avec des membres supplémentaires (bras, tentacules ou autres appendices) qui apparaissent lors de moments émotionnellement forts ou d''étapes importantes de la vie. Ces membres ont une conscience partielle."}'),
('hommes-betes', '{"nom":"Hommes-Bêtes","couleur":"#C8D8F0","image":"homme_bête.jpeg","population":315000,"esperanceVie":"30 à 180 ans selon l''espèce","description":"Les Hommes-Bêtes sont la race la plus nombreuse de Minamix. Hybrides humains-animaux, leurs capacités varient considérablement selon leur ascendance animale.","histoire":"Présents depuis les origines de Minamix, les Hommes-Bêtes comprennent une multitude de sous-espèces correspondant aux différents animaux. Ils ont développé des cultures variées influencées par leur nature animale respective.","magie":"Les capacités magiques des Hommes-Bêtes varient selon leur espèce animale. Certains ont des affinités naturelles pour certains éléments, d''autres possèdent des capacités physiques améliorées. Le pourcentage de mages varie selon les espèces.","societe":"Organisés en meutes, hardes ou clans selon leur nature animale, les Hommes-Bêtes ont leurs propres hiérarchies et traditions. Ils sont particulièrement nombreux à Lyndera où leur structure sociale clanique est valorisée.","physique":"Hybrides humains-animaux avec des caractéristiques physiques variées selon l''ascendance. Certains sont bipèdes avec des traits animaux (oreilles, queue, griffes), d''autres ont une apparence plus animale. Taille et force variables selon l''espèce."}')
on conflict (slug) do nothing;

-- ── Ryximus ───────────────────────────────────────────────────

insert into public.ryximus (slug, data) values
('whimir', '{"nom":"Whimir","genre":"Féminin","element":"Esprit","couleur":"#9B7EC8","image":"whimir.jpeg","citation":"Dernière née des Ryximus, elle incarne l''élément le plus énigmatique et insaisissable : l''esprit.","description":"Whimir est la plus jeune des Ryximus et la plus mystérieuse. Elle incarne l''esprit sous toutes ses formes — la pensée, la conscience, le rêve et la folie.","personnalite":"Distante et énigmatique, Whimir est fascinée par la psychologie humaine et la souffrance qu''elle engendre. Elle observe plus qu''elle n''agit, collectionnant les émotions des mortels comme d''autres collectionnent des objets précieux.","conditionPacte":"Surmonter des barrières psychologiques ou physiques significatives. Whimir n''accorde son pacte qu''à ceux qui ont traversé et dépassé leurs limites mentales."}'),
('noctis', '{"nom":"Noctis","genre":"Masculin","element":"Obscurité","couleur":"#2D2D5E","image":"noctis.jpeg","citation":"L''incarnation de la peur ; pas celle qu''on inspire mais celle que l''on ressent.","description":"Noctis incarne l''obscurité et la peur ressentie. Contrairement à ce qu''on pourrait attendre, il est la personnification non de la terreur qu''on inspire, mais de la vulnérabilité de celui qui craint.","personnalite":"Doux, anxieux et empathique malgré son domaine. Noctis comprend profondément la peur car il la ressent lui-même. Il est le protecteur de ceux qui tremblent dans le noir, non leur bourreau.","conditionPacte":"Vaincre ses peurs et phobies. Noctis accorde son pacte à ceux qui ont affronté ce qui les terrorisait le plus et l''ont surmonté."}'),
('vespera', '{"nom":"Vespera","genre":"Féminin","element":"Lumière","couleur":"#F5C842","image":"vespera.jpeg","citation":"Une incarnation de la lumière sous toutes ses formes : la chaleur réconfortante du matin.","description":"Vespera est l''incarnation de la lumière dans toutes ses manifestations — la clarté du jour, la chaleur du soleil, l''espoir et la guérison.","personnalite":"Énergique, altruiste et résiliente, Vespera a tendance à s''épuiser à force d''aider les autres. Elle est la plus interventionniste des Ryximus, toujours prête à agir pour alléger la souffrance des mortels.","conditionPacte":"Persévérer à travers les épreuves de la vie. Vespera accorde son pacte à ceux qui ont fait preuve d''une résilience remarquable face à l''adversité."}'),
('sylvae', '{"nom":"Sylvaë","genre":"Masculin","element":"Nature","couleur":"#4A7A3D","image":"sylvaë.jpeg","citation":"Incarne la lenteur, celle qu''on retrouve dans un chêne qui a pris mille ans à construire.","description":"Sylvaë est l''esprit de la nature dans ce qu''elle a de plus patient et de plus durable. Il représente les cycles naturels, la croissance lente et la sagesse qui vient avec le temps.","personnalite":"Patient, paisible et contemplatif, Sylvaë réfléchit toujours aux cycles naturels. Sa temporalité est différente des autres — là où ses frères et sœurs pensent en années, lui pense en siècles.","conditionPacte":"Être en harmonie avec la nature ou faire preuve d''une patience exceptionnelle. Sylvaë n''est pas pressé d''accorder son pacte."}'),
('ignir', '{"nom":"Ignir","genre":"Masculin","element":"Feu","couleur":"#E84A2F","image":"ignir.jpeg","citation":"L''incarnation de l''intensité, de cette flamme rebelle qui brûle dans chaque être.","description":"Ignir est le feu à l''état pur : l''intensité, la passion, la destruction créatrice et la chaleur vitale. Il représente tout ce qui brûle avec force, de la flamme d''un foyer à l''ambition d''un conquérant.","personnalite":"Intense, charismatique, impulsif et passionné. Ignir vit chaque instant comme si c''était le dernier. Sa présence est difficile à ignorer — il embrase tout ce qu''il touche, pour le meilleur et pour le pire.","conditionPacte":"Faire preuve d''une motivation ardente et d''une intensité égale à la sienne. Ignir n''accorde son pacte qu''à ceux qui brûlent d''une flamme aussi vive que la sienne."}'),
('galdros', '{"nom":"Galdros","genre":"Masculin","element":"Terre","couleur":"#7A5C30","image":"galdros.jpeg","citation":"Très stoïque, presque inexpressif en toutes circonstances, on pourrait croire qu''il a un cœur de pierre.","description":"Galdros est le plus ancien des Ryximus. Il incarne la terre dans ce qu''elle a de plus solide — la fondation, la permanence, la protection et le poids des responsabilités.","personnalite":"Stoïque, presque inexpressif, Galdros est un protecteur fiable pour ses frères et sœurs Ryximus. Il est celui qui maintient la stabilité quand tout autour semble vaciller. Son apparente froideur cache une profonde loyauté.","conditionPacte":"Être déterminé et fiable. Galdros favorise les individus qui font preuve d''une volonté inébranlable et d''une constance dans leurs engagements."}'),
('zoggan', '{"nom":"Zoggan","genre":"Féminin","element":"Air","couleur":"#A8D8EA","image":"zoggan.jpeg","citation":"N''a qu''un seul maître mot : la liberté.","description":"Zoggan est l''incarnation de l''air et de la liberté. Imprévisible comme le vent, elle ne peut être contrainte ni encadrée. Elle représente la liberté absolue, le voyage et le changement perpétuel.","personnalite":"Imprévisible, éprise de liberté, Zoggan fuit les responsabilités et les engagements. Elle apparaît et disparaît selon son bon vouloir, même parmi les Ryximus. Sa bonne humeur est contagieuse mais on ne peut jamais compter sur sa présence.","conditionPacte":"Avoir un désir profond de liberté. Zoggan accorde son pacte à ceux qui refusent d''être enfermés dans les conventions et aspirent à une existence libre de toute contrainte."}'),
('nyrel', '{"nom":"Nyrel","genre":"Féminin","element":"Eau","couleur":"#2E86AB","image":"nyrel.jpeg","citation":"Très franche, elle apprécie que les gens le soient en retour.","description":"Nyrel est l''incarnation de l''eau et des émotions. Comme l''eau qui prend la forme de son contenant, elle s''adapte mais conserve toujours sa nature profonde — fluide, sincère et profonde.","personnalite":"Très franche et émotionnellement expressive, Nyrel dit toujours ce qu''elle pense et attend la même chose en retour. Elle est généreuse avec ceux qui lui font confiance et impitoyable envers la fausseté.","conditionPacte":"Embrasser ses émotions ouvertement et sincèrement. Nyrel accorde son pacte à ceux qui ne cachent pas ce qu''ils ressentent et vivent avec authenticité."}')
on conflict (slug) do nothing;

-- ── Magie ─────────────────────────────────────────────────────

insert into public.magie (id, data) values (1, '{
  "intro": "La magie opère à travers des particules de mana invisibles à l''œil nu. Chaque utilisateur de magie possède un réservoir non physique de mana dont la capacité varie et croît avec l''entraînement et l''âge. Le mana se régénère passivement par absorption des particules ambiantes ou plus rapidement par la méditation.",
  "sections": [
    {"titre": "Qu''est-ce que le mana ?", "contenu": "Le mana est l''énergie fondamentale qui alimente toute magie dans Minamix. Il est présent partout dans l''air, la terre et les êtres vivants sous forme de particules invisibles. Les mages apprennent à percevoir, absorber et contrôler ces particules pour effectuer des sorts. La capacité d''un mage est déterminée par la taille de son réservoir de mana, qui peut être développé avec la pratique et l''âge."},
    {"titre": "Consommation de mana", "contenu": "Le coût en mana des sorts varie considérablement. Certains drainant continuellement tant qu''ils sont actifs, d''autres consommant une quantité fixe à l''activation. Les sorts de haut niveau peuvent nécessiter des carburants supplémentaires au-delà du mana, impliquant potentiellement un sacrifice personnel. Dépasser son réservoir de mana est extrêmement dangereux et peut provoquer des blessures graves ou la mort."},
    {"titre": "Types de sorts", "contenu": "Il existe deux grandes catégories de sorts : les sorts communs (activation simple, faible coût en mana) et les sorts avancés (complexes, nécessitant des instructions multiples). Nommer un sort le renforce et aide à la concentration. La formulation des incantations joue un rôle crucial dans la précision et la puissance du résultat."},
    {"titre": "Cercles de magie", "contenu": "Chronophages mais puissants, les cercles de magie nécessitent l''inscription de runes autour de cercles pour en spécifier les paramètres. Ils tirent leur origine du langage des dieux eux-mêmes et consomment à la fois le mana du lanceur et le mana ambiant. Un cercle bien construit peut accomplir des effets impossibles à réaliser autrement."},
    {"titre": "Magie sauvage", "contenu": "Pratiquée intuitivement à Ilonaï sans incantations, la magie sauvage permet une plus grande liberté créative mais exige une concentration intense. Elle est plus imprévisible que la magie académique mais peut produire des effets surprenants. Les utilisateurs de magie sauvage développent une connexion émotionnelle profonde avec les éléments naturels."},
    {"titre": "Affinités et apprentissage", "contenu": "La capacité magique est innée. Les utilisateurs possèdent des affinités élémentaires (rarement deux) qui accordent une maîtrise plus aisée de la magie liée. L''éducation formelle est attendue dans la plupart des régions, notamment à Silfus, Lyndera et Frimaz. À Ilonaï, les anciens transmettent la connaissance de façon orale et pratique."}
  ],
  "affinites": [
    {"element": "Feu", "description": "Flammes, chaleur, destruction et création"},
    {"element": "Eau", "description": "Flots, glace, guérison et purification"},
    {"element": "Terre", "description": "Roche, métal, protection et permanence"},
    {"element": "Air", "description": "Vent, foudre, vitesse et liberté"},
    {"element": "Nature", "description": "Plantes, animaux, croissance et cycle"},
    {"element": "Lumière", "description": "Clarté, soin, illusion et révélation"},
    {"element": "Obscurité", "description": "Ombres, peur, invisibilité et secrets"},
    {"element": "Esprit", "description": "Pensée, rêve, conscience et volonté"}
  ]
}')
on conflict (id) do nothing;

-- ── Annexes ───────────────────────────────────────────────────

insert into public.annexes (label, data)
select label, jsonb_build_object('titre', 'Annexe ' || label, 'contenu', '')
from unnest(array['A','B','C','D','E','F','G','H']) as label
on conflict (label) do nothing;
